# Generated by Django 4.2.5 on 2023-11-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0036_alter_resume_resume_objective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='skill',
            field=models.TextField(),
        ),
    ]
