# Generated by Django 4.2.5 on 2023-11-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0037_alter_resume_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='allprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
