# Generated by Django 4.2.5 on 2023-11-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0038_allprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allprofile',
            name='emp_count',
            field=models.IntegerField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allprofile',
            name='subsidiaries_count',
            field=models.IntegerField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
