# Generated by Django 4.2.5 on 2023-11-09 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userFolder', '0008_alter_account_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordProcessToGetReco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_to', models.CharField(max_length=255)),
                ('char_count', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TimeToGetCompatibilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_to', models.CharField(max_length=255)),
                ('char_count', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GetDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='images/')),
                ('tor', models.FileField(blank=True, null=True, upload_to='images/')),
                ('nbi', models.FileField(blank=True, null=True, upload_to='images/')),
                ('psa', models.FileField(blank=True, null=True, upload_to='images/')),
                ('fk_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userFolder.account')),
            ],
        ),
    ]
