# Generated by Django 4.2.5 on 2023-11-09 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0029_remove_applicants_sched_alter_applicants_applied'),
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogUserEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.jobpost')),
            ],
        ),
    ]
